# Copyright 2015 Google Inc. All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
"""Utilities to configure the dispatcher, middleware and environment."""

import logging
import os
import threading
from UserDict import UserDict

from google.appengine.api import appinfo_includes
from google.appengine.runtime import wsgi


def get_module_config_filename():
  """Returns the name of the module configuration file (app.yaml)."""
  module_yaml_path = os.environ['MODULE_YAML_PATH']
  logging.info('Using module_yaml_path from env: %s', module_yaml_path)
  return module_yaml_path


def get_module_config(filename):
  """Returns the parsed module config."""
  with open(filename) as f:
    return appinfo_includes.Parse(f)


def app_for_script(script):
  """Returns the WSGI app specified in the input string, or None on failure."""
  if script:
    app, filename, err = wsgi.LoadObject(script)  # pylint: disable=unused-variable
    if err:
      # Log the exception but do not reraise.
      logging.exception('Failed to import %s: %s', script, err)
      return None
    else:
      return app_wrapped_in_user_middleware(app)


def app_wrapped_in_user_middleware(app):
  """Returns the input WSGI app, wrapped in appengine_config middleware."""
  add_middleware = get_add_middleware_from_appengine_config()
  if add_middleware:
    return add_middleware(app)
  else:
    return app


def get_add_middleware_from_appengine_config():
  """Tries to import appengine_config and return middleware; fails silently.

  `env_config` is optionally part of GAE-compatible user code.
  If the user chooses to define the `webapp_add_wsgi_middleware` function
  there, then we will use it to wrap app scripts. This is used for e.g.
  appstats. Many user apps do not have or need env_config, so failure
  to import it or failure to find `webapp_add_wsgi_middleware` is not an
  error.

  Returns:
    The appengine_config.webapp_add_wsgi_middleware function or None.
  """
  try:
    import appengine_config  # pylint: disable=g-import-not-at-top
    try:
      return appengine_config.webapp_add_wsgi_middleware
    except AttributeError:
      return None
  except ImportError:
    return None


def load_user_scripts_into_handlers(handlers):
  """Preloads user scripts, wrapped in env_config middleware if present.

  Args:
    handlers: appinfo_external.handlers data as provided by get_module_config()

  Returns:
    A list of tuples suitable for configuring the dispatcher() app,
    where the tuples are (url, script, app):
      - url: The url pattern which matches this handler.
      - script: The script to serve for this handler, as a string.
      - app: The fully loaded app corresponding to the script.
  """
  loaded_handlers = [
      (x.url,
       x.script.replace('$PYTHON_LIB/', '') if x.script else x.script,
       app_for_script(x.script) if x.script else None)
      for x in handlers]
  logging.info('Parsed handlers: %s',
               [(url, script) for (url, script, _) in loaded_handlers])
  return loaded_handlers


def env_vars_from_env_config(env_config):
  """Generate a dict suitable for updating os.environ to reflect app config.

  This function only returns a dict and does not update os.environ directly.

  Args:
    env_config: The app configuration as generated by
                vmconfig.BuildVmAppengineEnvConfig()

  Returns:
    A dict of strings suitable for e.g. `os.environ.update(values)`.
  """

  return {'SERVER_SOFTWARE': env_config.server_software,
          'APPENGINE_RUNTIME': 'python27',
          'APPLICATION_ID': '%s~%s' % (env_config.partition,
                                       env_config.appid),
          'INSTANCE_ID': env_config.instance,
          'BACKEND_ID': env_config.major_version,
          'CURRENT_MODULE_ID': env_config.module,
          'CURRENT_VERSION_ID': '%s.%s' % (env_config.major_version,
                                           env_config.minor_version),
          'DEFAULT_TICKET': env_config.default_ticket}


def user_env_vars_from_appinfo(appinfo):
  """Generate a dict of env variables specified by the user in app.yaml.

  This function only returns a dict and does not update os.environ directly.

  Args:
    appinfo: The configuration info (a parsed yaml object) as generated by
              get_module_config()

  Returns:
    A dict of strings suitable for e.g. `os.environ.update(values)`.
  """

  return appinfo.env_variables or {}


# Dictionary with thread-local contents.
class ThreadLocalDict(UserDict, threading.local):
  pass
